language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: nmkgGNy9fYbR/+Xvht+Wv9fmQno8QYgktk7FV688ujVnixNydj6grhiURhgzzxpV+m8BM/ntdaOTo6BPcI4CrJewo93EXc7vUyy7exPSw3W0yySbQhjsXGdKUlBrgU1DnKpFVrUnpsjtje0JNgyp3gQOnasNADMuKNPuB5yZmtW5iglsfxUVa6HGdYDR+50v544cDBJHCp0FayE8hIqcH3pwMyYc060c3RMZxRTDBC5c9xuVU6feTj1dFef+Rw8q5HjqUBpK0nmCpue84QODhErl3ulNXywUIJ8TeuVWTuY1pBpMrjjBhfiI69bvUKIZWH7EboM7RNRu9uyQ5QIsf7dzONjvDPQ35G7rf0UA++qTSYR5J+qMBYfPt4jVGjl0hB8/gMK2YlsLz8HXSOscz7RbidCuV1Q1NZ+EIs0LXuVMv1lDRND+VI+M+hyOSTEU3IoxTEgRqoKXcUh1QPaOjqXFqAS4V9yJUg0wYhcxVZ4O9DbqHOihSW2ffUuHENMUpBCTZMm27fLYbm/mwjRYyeKll1azCcPDrJ7ZySI8cqaYtYpwDhCUm+3o0rHi4pJ2aR5+PGcQCO0m+QgRKsTJS5C7Ipc+0/Aarowlec/33p3bbQF6xM1Ndd6DRyzl1JlUg7Uzw41PI97IXd4N4yY7sJYh8ri73cKVuPFUUQOPKlQ=
true:
  branch: master
